config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # root to: "user#index"
  root 'user#index'
  get 'user/index'
  resources :comics
  resources :movies
  resources :games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  validates :year, presence: true
  validates :title, presence: true
  validates :abstract, presence: true
  validates :status, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true
  validates :platform, presence: true
  validates :status, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :year, presence: true
  validates :title, presence: true
  validates :abstract, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  # GET /comics or /comics.json
  def index
    @q = Comic.ransack(params[:q])
    @comics = @q.result(distinct: true).page(params[:page])
  end

  # GET /comics/1 or /comics/1.json
  def show
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics or /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: "Comic was successfully created." }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1 or /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: "Comic was successfully updated." }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1 or /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: "Comic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comic_params
      params.require(:comic).permit(:year, :title, :abstract, :status)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  # GET /games or /games.json
  def index
    @q = Game.ransack(params[:q])
    @games = @q.result(distinct: true).page(params[:page])

  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :platform, :status)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]


  # GET /movies or /movies.json
  def index
    @q = Movie.ransack(params[:q])
    @movies = @q.result(distinct: true).page(params[:page])
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:year, :title, :abstract, :status)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only:[]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comics/_form.html.erb
<%= form_with(model: comic, local: true) do |form| %>
  <% if comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comic.errors.count, "error") %> exist</h2>

      <ul>
        <% comic.errors.full_messages.each do |message| %>
          <li class="alert-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :abstract %>
    <%= form.text_area :abstract, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :status %>
    <%= form.select :status ,["todo", "doing", "done"] ,{} , class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Comic Lists", class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Editing Comic</h1>

  <%= render 'form', comic: @comic %>

  <%= link_to 'Show', @comic, class: "btn btn-warning mt-2 mb-3" %>
  <%= link_to 'Back', comics_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/comics/index.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <%= search_form_for @q do |f| %>
      <%= f.label :year_or_title_or_abstract_or_status, "Search Keywords", class: "mt-2" %>
      <%= f.search_field :year_or_title_or_abstract_or_status_cont, class: "form-control mb-2" %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-3"></div>
</div>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="mt-3">Comics</h1>

    <table class="table">
      <thead>
      <tr>
        <th><%= sort_link(@q, :year, "Year") %></th>
        <th><%= sort_link(@q, :title, "Title") %></th>
        <th><%= sort_link(@q, :abstract, "Abstract") %></th>
        <th><%= sort_link(@q, :status, "Status") %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @comics.each do |comic| %>
        <tr>
          <td><%= comic.year %></td>
          <td><%= comic.title %></td>
          <td><%= comic.abstract %></td>
          <% case comic.status %>
          <% when "todo" %>
            <td class="alert-warning"><%= comic.status %></td>
          <% when "doing" %>
            <td class="alert-success"><%= comic.status %></td>
          <% when "done" %>
            <td class="alert-secondary"><%= comic.status %></td>
          <% end %>
          <td><%= link_to 'Show', comic %></td>
          <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
          <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>
    <%= paginate @comics %>
    <%= link_to 'New Comic', new_comic_path, class: "btn btn-primary mb-5"%>
  </div>
  <div class="col-2"></div>
</div>

app/views/comics/new.html.erb
<div class="col-md-4 offset-md-4">
  <h1 class="mt-3">New Comic</h1>

  <%= render 'form', comic: @comic %>

  <%= link_to 'Back', comics_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/comics/show.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <table class="table">
      <thead>
      <tr>
        <th>Year</th>
        <th>Title</th>
        <th>Abstract</th>
        <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @comic.year %></td>
        <td><%= @comic.title %></td>
        <td><%= @comic.abstract %></td>
        <td><%= @comic.status %></td>
      </tr>
      </tbody>
    </table>
    <%= link_to 'Edit', edit_comic_path(@comic), class: "btn btn-success mb-3" %>
    <%= link_to 'Back', comics_path, class: "btn btn-secondary mb-3" %>
  </div>
  <div class="col-2"></div>
</div>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> exist</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li class="alert-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_group">
    <%= form.label :title%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :platform %>
    <%= form.text_field :platform, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= form.select :status ,["todo", "doing", "done"] ,{}, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Game Lists", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Editing Game</h1>

  <%= render 'form', game: @game %>

  <%= link_to 'Show', @game, class: "btn btn-warning mt-2 mb-3" %>
  <%= link_to 'Back', games_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/games/index.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <%= search_form_for @q do |f| %>
      <%= f.label :title_or_platform_or_status, "Search Keywords", class: "mt-2" %>
      <%= f.search_field :title_or_platform_or_status_cont, class: "form-control mb-2" %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-3"></div>
</div>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="mt-3">Games</h1>

    <table class="table">
      <thead>
      <tr>
        <th><%= sort_link(@q, :title, "Title") %></th>
        <th><%= sort_link(@q, :platform, "Platform") %></th>
        <th><%= sort_link(@q, :status, "Status") %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.title %></td>
          <td><%= game.platform %></td>
          <% case game.status %>
          <% when "todo" %>
            <td class="alert-warning"><%= game.status %></td>
          <% when "doing" %>
            <td class="alert-success"><%= game.status %></td>
          <% when "done" %>
            <td class="alert-secondary"><%= game.status %></td>
        <% end %>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>
    <%= paginate @games %>
    <%= link_to 'New Game', new_game_path, class: "btn btn-primary mb-5" %>
  </div>
  <div class="col-2"></div>
</div>

app/views/games/new.html.erb
<div class="col-md-4 offset-md-4">
  <h1 class="mt-3">New Game</h1>

  <%= render 'form', game: @game %>

  <%= link_to 'Back', games_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/games/show.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <table class="table">
      <thead>
      <tr>
        <th>Title</th>
        <th>Platform</th>
        <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @game.title %></td>
        <td><%= @game.platform %></td>
        <td><%= @game.status %></td>
      </tr>
      </tbody>
    </table>
    <%= link_to 'Edit', edit_game_path(@game), class: "btn btn-success mb-3" %>
    <%= link_to 'Back', games_path, class: "btn btn-secondary mb-3" %>
  </div>
  <div class="col-2"></div>

</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8 mt-3">
      <p class="text-light text-center">©Copyright 2021 Tracking My Hobbies All Rights Reserved.</p>
      <br>
      <p class="text-warning text-center">My E-mail-address: kiyokiyopip56@gmail.com</p>
      <p class="text-warning text-center">Please contact me!!!</p>
    </div>
    <div class="col-2"></div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Tracking Hobbies", '/user/index', class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", '/user/index', class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Login", '/users/sign_in', class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Games", games_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Movies", movies_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Comics", comics_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_notification.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracking Hobbies</title>
    <%= favicon_link_tag('servicestack-brands.svg') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notification' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> exist</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li class="alert-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :abstract %>
    <%= form.text_area :abstract, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :status %>
    <%= form.select :status ,["todo", "doing", "done"] ,{} , class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Movie Lists", class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="col-md-4 offset-md-4">
  <h1>Editing Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Show', @movie, class: "btn btn-warning mt-2 mb-3" %>
  <%= link_to 'Back', movies_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/movies/index.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <%= search_form_for @q do |f| %>
      <%= f.label :year_or_title_or_abstract_or_status, "Search Keywords", class: "mt-2" %>
      <%= f.search_field :year_or_title_or_abstract_or_status_cont, class: "form-control mb-2" %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-3"></div>
</div>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="mt-3">Movies</h1>

    <table class="table">
      <thead>
      <tr>
        <th><%= sort_link(@q, :year, "Year") %></th>
        <th><%= sort_link(@q, :title, "Title") %></th>
        <th><%= sort_link(@q, :abstract, "Abstract") %></th>
        <th><%= sort_link(@q, :status, "Status") %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.year %></td>
          <td><%= movie.title %></td>
          <td><%= movie.abstract %></td>
          <% case movie.status %>
          <% when "todo" %>
            <td class="alert-warning"><%= movie.status %></td>
          <% when "doing" %>
            <td class="alert-success"><%= movie.status %></td>
          <% when "done" %>
            <td class="alert-secondary"><%= movie.status %></td>
          <% end %>
          <td><%= link_to 'Show', movie %></td>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>
    <%= paginate @movies %>
    <%= link_to 'New Movie', new_movie_path, class: "btn btn-primary mb-5" %>
  </div>
  <div class="col-2"></div>
</div>

app/views/movies/new.html.erb
<div class="col-md-4 offset-md-4">
  <h1 class="mt-3">New Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Back', movies_path, class: "btn btn-secondary mt-2 mb-3" %>
</div>

app/views/movies/show.html.erb
<p id="notice" class="alert-success"><%= notice %></p>

<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <table class="table">
      <thead>
      <tr>
        <th>Year</th>
        <th>Title</th>
        <th>Abstract</th>
        <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @movie.year %></td>
        <td><%= @movie.title %></td>
        <td><%= @movie.abstract %></td>
        <td><%= @movie.status %></td>
      </tr>
      </tbody>
    </table>
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-secondary mb-3" %>
    <%= link_to 'Back', movies_path, class: "btn btn-success mb-3" %>
  </div>
  <div class="col-2"></div>
</div>

app/views/user/index.html.erb
<header class="container-fluid mb-3">
  <div class="align-middle pt-5 text-center text-light">
    <h1 class="pt-5 pb-5 display-3 font-weight-normal">What I played?</h1>
    <h1 class="pt-5 text-uppercase display-4">Solve this question!!</h1>
  </div>
</header>
<div class="container overflow-hidden mb-5">
  <div class="text-center text-dark mt-5 mb-5">
    <h1>SERVICES</h1>
  </div>
  <div class="row text-center">
    <div class="col-md-4">
      <img src="/assets/game.png" width="150" height="150">
      <div class="text-center mt-2">
        <h2>Game</h2>
        <p class="text-secondary">何のゲームをやったかもしくはやりたいかなど、自分の好きなように書き溜めることができます。</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src="/assets/book.png" width="150" height="150">
      <div class="text-center mt-2">
        <h2>Comic</h2>
        <p class="text-secondary">何の漫画を読んだかもしくは読みたいかなど、自分の好きなように書き溜めることができます。</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src="/assets/film.png" width="150" height="150">
      <div class="text-center mt-2">
        <h2>Movie</h2>
        <p class="text-secondary">何の映画を見たかもしくは見たいかなど、自分の好きなように書き溜めることができます。</p>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>